const PhoneActionTypes = {
  FETCH_PHONE_LIST_START: 'FETCH_PHONE_LIST_START',
  FETCH_PHONE_LIST_SUCCESS: 'FETCH_PHONE_LIST_SUCCESS',
  FETCH_PHONE_LIST_FAILURE: 'FETCH_PHONE_LIST_FAILURE',
}

export default PhoneActionTypes;